### ISSUE TITLE
Trying to access https://ngrok.localhost.direct:8443/ outside the network but it is not accessible

### ISSUE THREAD

**Issue by cay-cospete** [igops/ngrok-skip-browser-warning#3]
Hey Igops,

I am trying to access `https://ngrok.localhost.direct:8443/` outside my network lets say on my phone but it is showing this site cant be reached

**Comment by cay-cospete** [comment]
I think this only works when someone has sent you the URL but is there a way to make this work if i am the creator and i am sending the URL to someone else ? Because i dont think everyone will have docker installed to bypass this.

**Comment by igops** [comment]
Hi @cay-cospete,

According to the [disclaimer](https://github.com/igops/ngrok-skip-browser-warning#disclaimer), the purpose of this docker image is to ease your development process, literally to add the `ngrok-skip-browser-warning` header to all requests sent from the machine where this container is running [**A**] to the machine where you host the API service behind ngrok proxy [**B**].

Since you are trying to reach the API service from a mobile phone [**C**], this approach will not work out of the box.

Possible workarounds for you are:
1\. Get the [ngrok subscription](https://ngrok.com/pricing). Then, you can reach your API from everywhere without polluting your API responses with the warnings.

2\. If you can make device **A** reachable from **C** (e.g. by joining same home/office WiFi), then you can do the following trick:
:heavy_check_mark: Register a free FQDN pointing to your local IP address of **A**. This can be done using [DuckDNS](https://www.duckdns.org/domains) or analogs.  
:heavy_check_mark: Receive free SSL certificates using [Certbot + DuckDNS plugin](https://pypi.org/project/certbot-dns-duckdns/), or [manually](https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-dns-validation-with-acme-dns-certbot-on-ubuntu-18-04) proving you can control the DNS records.  
:heavy_check_mark: Run my container on the device **A** overriding the `PROXY_HOST_REST` value and mounting your [own certificates](https://github.com/igops/ngrok-skip-browser-warning#env-variables):
```shell
$ docker run -d --rm \
  -p 8443:443 \
  -p 8080:80 \
  -e NGROK_HOST=https://your-ngrok-domain.ngrok.io \
  -e PROXY_HOST_REST=domain-pointing-device-a \
  -e PROXY_SSL_CERT_NAME=your-ssl-crt-name.crt \
  -e PROXY_SSL_KEY_NAME=your-ssl-key-name.key \
  -v /path/to/ssl/certs:/etc/nginx/certs \
  igops/ngrok-skip-browser-warning:latest
```
:heavy_check_mark: Access your API from the device **C** using `https://domain-pointing-device-a/` as base URL.

**Comment by cay-cospete** [comment]
Hey @igops Thank you for you response !

It is not just mobile phone but in general accessing it anywhere outside the network. Lets say i am [A] and [B] both i am only running my local server then pointing it to `ngrok http port` like so and then running the container with URL which ngrok provides now i want some URL to be generated which i can provide lets say to different teams like QE, Product team, Designers etc which will never be in my network. I know having ngrok subscription would solve this but currently we cant subscribe to it. Do you have anyway other way to do this ?

**Comment by igops** [comment]
@cay-cospete I understand the setup you are addressing.

A possible solution could be running an additional proxy server on some public cloud (AWS/GCP/Azure) which would retranslate the requests from your staff to your ngrok endpoint. Note, there are [free tiers](https://cloud.google.com/free/docs/free-cloud-features#compute) offering small VMs with a shared core, which should be enough for a simple proxy like yours. However, as far as I remember, a free ngrok tunnel is not production-ready (not stable), so that you should conduct a resilience of your setup by yourself.

P.S. I'm working on a zero-trust hobbyist project at the moment which is supposed to provide similar setups for the development teams (without ngrok). Kindly invite you keeping in touch if you are interested 🙌.

**Comment by igops** [comment]
I'm closing this thread as the requested setup is out of scope of this project.

**Comment by cay-cospete** [comment]
@igops Hey thanks a lot for you response, truly appreciate it. Yes i am interested :) even though i am not that sound in all these tools :/
