### ISSUE TITLE
Is this a success? What should I do next?

### ISSUE THREAD

**Issue by zlh-source** [igops/ngrok-skip-browser-warning#4]
Here are my execution steps.

Step 1: 
Run the ngrok:
```
ngrok http http://localhost:8010
```
and I get :
```
https://8cc3-36-133-141-100.ngrok-free.app -> http://localhost:8010  
```

Step 2:
Run your docker, like this:
![53ca2c45a4c9ccc230290292493b539](https://github.com/igops/ngrok-skip-browser-warning/assets/50194803/edaf2b7e-50e5-4b39-9efc-e9654fc2a305)

I don't understand. Is this successful? What should I do next?

Thanks.

**Comment by igops** [comment]
Hi @zlh-source, please take a look at the [topology diagram](https://github.com/igops/ngrok-skip-browser-warning?tab=readme-ov-file#solution).

The docker container must be run on that device from where you send requests to ngrok (device A). Implying ngrok agent is running on device B.

Running the container on the same machine as ngrok agent would not make any impact to the warning page.

**Comment by shillingg** [comment]
1. Start a ngrok tunnel
`ngrok http 80 `
Get the ngrok Forward https URL
https://5e6b-66-30-112-86.ngrok-free.app/

2. Create a Docker container to create a HTTPS forward proxy.
```
docker run -d --rm \
  -p 8443:443 \
  -p 8080:80 \
  -e NGROK_HOST=https://5e6b-66-30-112-86.ngrok-free.app\
  igops/ngrok-skip-browser-warning:latest
```

3. Is this the new URL to use on the target machine going through the Docker proxy? I am not able to get a connection. Why?  
https://ngrok.localhost.direct:8443/5e6b-66-30-112-86.ngrok-free.app/

Just so I understand. If you wanted to change the ngrok port to something else like "400" would it work like this?
`ngrok http 400`

```
docker run -d --rm \
  -p 8443:443 \
  -p 8080:400 \
  -e NGROK_HOST=https://5e6b-66-30-112-86.ngrok-free.app\
  igops/ngrok-skip-browser-warning:latest
```
URL to use on the target machine, but not able to connect
https://ngrok.localhost.direct:8443/5e6b-66-30-112-86.ngrok-free.app/

Looks like I should have put this question in a different place...

**Comment by igops** [comment]
Hi @shillingg,

In your first case, you should use just https://ngrok.localhost.direct:8443 on the machine, *from were you send the requests to ngrok*. No need to add `/5e6b-66-30-112-86.ngrok-free.app` to the requests.

In your second case, there's no need to change anything on the proxy side. Just run `ngrok http 400`, receive your ngrok address and pass it to a docker run. No need to change the port publishing in docker.

Please ensure your setup matches the [topology diagram](https://github.com/igops/ngrok-skip-browser-warning?tab=readme-ov-file#solution).

**Comment by shillingg** [comment]
Hi Igops!

Maybe I'm not understanding the the topology diagram correctly. Here is my setup:

Kali virtual machine with ngrok and igops and Apache webserver on it (I was thinking this was like Device A in the diagram) -->  Windows 11 machine (I was thinking this was like Device B in the diagram).

1. Start a ngrok tunnel on Kali VM machine
`ngrok http 80` 
Get the ngrok Forward https URL
https://5e6b-66-30-112-86.ngrok-free.app/ 

2. Create a Docker container to create a HTTPS forward proxy.
```
docker run -d --rm \
  -p 8443:443 \
  -p 8080:80 \
  -e NGROK_HOST=https://5e6b-66-30-112-86.ngrok-free.app\
  igops/ngrok-skip-browser-warning:latest
```

3. This the new URL to use on the target machine going through the Docker proxy. Not sure how the Windows machine would be able to find this URL as it doesn't link the the ngrok Webpage or URL. Still not able to get a connection :(
https://ngrok.localhost.direct:8443                                                      # Thank you for explaining this!

4. Error on the windows machine 
![image](https://github.com/igops/ngrok-skip-browser-warning/assets/23301576/eb54553c-e633-4bab-b421-bdbc80267ea5)

5. Error on the Kali machine. I also tried the link on the Kali machine, just to see what it would do. It would make sense that the link might work on the Kali machine since the URL is going to that machine. This doesn't work for what I'm trying to do, but might a well figure out how to get igops to work now lol.   
![Screenshot from 2024-06-07 17-29-54](https://github.com/igops/ngrok-skip-browser-warning/assets/23301576/3302ec61-5266-49ab-be14-9615a263405a)

"Edges" looks to be a setting in the ngrok dashboard.
